site_name: Lupaxa CertTool
site_description: "Generate self-signed certificates, CSRs, and keys from CLI or Python."
site_url: https://lupaxa-security-toolbox.github.io/certtool/
repo_url: https://github.com/lupaxa-security-toolbox/certtool
repo_name: lupaxa-security-toolbox/certtool

docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  icon:
    repo: fontawesome/brands/github

copyright: |
  <p class="lupaxa-footer">
    <strong>&copy; The Lupaxa Project.</strong><br />
    <em>
      Where exploration meets precision.<br />
      Where the untamed meets the engineered.
    </em>
  </p>

extra:
  generator: false

# Custom CSS to inject Lupaxa colours
extra_css:
  - css/palette.css

# "Edit this page" links
edit_uri: edit/main/docs/

markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - CLI Quick Start: cli.md
  - Configuration Overview: configuration.md
  - Examples: examples.md
  - Security: security.md
  - Reference:
      - CLI: reference/cli.md
      - Config files: reference/config.md
      - Cert generation API: reference/certs.md
      - Example helpers: reference/example.md
      - Exceptions: reference/exceptions.md
      - Utils: reference/utils.md
      - Versioning: reference/version.md
  - Development:
      - Versioning & Releases: developer/versioning.md
  - Version: version.md
