name: Publish to TestPyPI

on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+rc[0-9]+'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build and upload to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c  # v6.0.0
        with:
          python-version: "3.13"

      - name: Install build backend (hatch)
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build distribution (sdist + wheel)
        run: |
          hatch build

      # Trusted publishing to TestPyPI
      # Make sure you have added this GitHub repo as a "Trusted Publisher"
      # in your TestPyPI project settings.
      - name: Publish to TestPyPI via trusted publisher
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/

  generate-release-notes:
    name: Generate Release Notes
    uses: the-lupaxa-project/.github/.github/workflows/reusable-generate-release.yml@master
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  status-check:
    name: Check Jobs Status
    needs:
      - build-and-publish
      - generate-release-notes
    if: always()
    # ðŸ”´ IMPORTANT: this is a *job-level* uses, not under steps:
    uses: the-lupaxa-project/.github/.github/workflows/reusable-check-jobs-status.yml@master

