name: Purge Deprecated Workflow Runs

on:
  workflow_dispatch:

  schedule:
    - cron: '33 3 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  purge:
    name: Run Purge Deprecated Workflow Runs
    uses: the-lupaxa-project/.github/.github/workflows/reusable-purge-deprecated-workflow-runs.yml@master

  status-check:
    name: Check Jobs Status
    needs:
      - purge
    if: always()
    # ðŸ”´ IMPORTANT: this is a *job-level* uses, not under steps:
    uses: the-lupaxa-project/.github/.github/workflows/reusable-check-jobs-status.yml@master
